# Generated by Django 5.2.8 on 2025-11-29 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chais/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('MASALA', 'Masala Chai'), ('GINGER', 'Ginger Chai'), ('CARDAMOM', 'Cardamom Chai'), ('SUGAR', 'Sugar Chai'), ('MILK', 'Milk Chai')], max_length=10)),
            ],
        ),
    ]
